// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ctrlkm.proto

package ctrlkm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The login request message containing the user's credentials
type UserCredentials struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCredentials) Reset()         { *m = UserCredentials{} }
func (m *UserCredentials) String() string { return proto.CompactTextString(m) }
func (*UserCredentials) ProtoMessage()    {}
func (*UserCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a75ea20cb76fa5, []int{0}
}

func (m *UserCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCredentials.Unmarshal(m, b)
}
func (m *UserCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCredentials.Marshal(b, m, deterministic)
}
func (m *UserCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCredentials.Merge(m, src)
}
func (m *UserCredentials) XXX_Size() int {
	return xxx_messageInfo_UserCredentials.Size(m)
}
func (m *UserCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_UserCredentials proto.InternalMessageInfo

func (m *UserCredentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserCredentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// The response message containing the user's authentication claims
type AuthClaims struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Userid               string   `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role                 int64    `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthClaims) Reset()         { *m = AuthClaims{} }
func (m *AuthClaims) String() string { return proto.CompactTextString(m) }
func (*AuthClaims) ProtoMessage()    {}
func (*AuthClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a75ea20cb76fa5, []int{1}
}

func (m *AuthClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthClaims.Unmarshal(m, b)
}
func (m *AuthClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthClaims.Marshal(b, m, deterministic)
}
func (m *AuthClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthClaims.Merge(m, src)
}
func (m *AuthClaims) XXX_Size() int {
	return xxx_messageInfo_AuthClaims.Size(m)
}
func (m *AuthClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthClaims.DiscardUnknown(m)
}

var xxx_messageInfo_AuthClaims proto.InternalMessageInfo

func (m *AuthClaims) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthClaims) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *AuthClaims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthClaims) GetRole() int64 {
	if m != nil {
		return m.Role
	}
	return 0
}

func init() {
	proto.RegisterType((*UserCredentials)(nil), "ctrlkm.UserCredentials")
	proto.RegisterType((*AuthClaims)(nil), "ctrlkm.AuthClaims")
}

func init() { proto.RegisterFile("ctrlkm.proto", fileDescriptor_73a75ea20cb76fa5) }

var fileDescriptor_73a75ea20cb76fa5 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xad, 0xfd, 0x83, 0x0e, 0x82, 0x30, 0x88, 0x96, 0x9e, 0x4a, 0x4f, 0x3d, 0xf5, 0xa0,
	0xe0, 0x5d, 0xe2, 0x4d, 0x4f, 0x05, 0x3f, 0x40, 0xb4, 0xc1, 0x0d, 0x4d, 0x32, 0x65, 0x92, 0xb2,
	0x5f, 0x7f, 0x21, 0x6d, 0xb7, 0xcb, 0xde, 0xe6, 0xc7, 0xe3, 0xf1, 0xe6, 0x07, 0x0f, 0x7f, 0x81,
	0xcd, 0x68, 0xbb, 0x89, 0x29, 0x10, 0x16, 0x0b, 0x35, 0x02, 0x1e, 0x7f, 0xbc, 0x62, 0xc1, 0x6a,
	0x50, 0x2e, 0x68, 0x69, 0x3c, 0x3e, 0x41, 0xae, 0xac, 0xd4, 0xa6, 0x4c, 0xea, 0xa4, 0xbd, 0xef,
	0x17, 0xc0, 0x0a, 0xee, 0x26, 0xe9, 0xfd, 0x91, 0x78, 0x28, 0x6f, 0x63, 0x70, 0xe6, 0x66, 0x00,
	0xf8, 0x98, 0xc3, 0x41, 0x18, 0xa9, 0x6d, 0xec, 0x07, 0x1a, 0x95, 0xdb, 0xfa, 0x11, 0xf0, 0x19,
	0x8a, 0xd9, 0x2b, 0xd6, 0x5b, 0x7b, 0xa5, 0x7d, 0x2d, 0xbd, 0x5c, 0x43, 0xc8, 0x98, 0x8c, 0x2a,
	0xb3, 0x3a, 0x69, 0xd3, 0x3e, 0xde, 0xaf, 0x9f, 0x00, 0x82, 0x5c, 0x60, 0x32, 0x5f, 0xd2, 0xe2,
	0x3b, 0xe4, 0xdf, 0xf4, 0xaf, 0x1d, 0xbe, 0x74, 0xab, 0xd8, 0x95, 0x47, 0x85, 0x5b, 0xb0, 0xff,
	0xd6, 0xdc, 0xfc, 0x16, 0xd1, 0xff, 0xed, 0x14, 0x00, 0x00, 0xff, 0xff, 0x57, 0x67, 0xa6, 0x27,
	0x0f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlKamClient is the client API for ControlKam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlKamClient interface {
	// Sends a greeting
	Login(ctx context.Context, in *UserCredentials, opts ...grpc.CallOption) (*AuthClaims, error)
}

type controlKamClient struct {
	cc *grpc.ClientConn
}

func NewControlKamClient(cc *grpc.ClientConn) ControlKamClient {
	return &controlKamClient{cc}
}

func (c *controlKamClient) Login(ctx context.Context, in *UserCredentials, opts ...grpc.CallOption) (*AuthClaims, error) {
	out := new(AuthClaims)
	err := c.cc.Invoke(ctx, "/ctrlkm.ControlKam/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlKamServer is the server API for ControlKam service.
type ControlKamServer interface {
	// Sends a greeting
	Login(context.Context, *UserCredentials) (*AuthClaims, error)
}

func RegisterControlKamServer(s *grpc.Server, srv ControlKamServer) {
	s.RegisterService(&_ControlKam_serviceDesc, srv)
}

func _ControlKam_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlKamServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ctrlkm.ControlKam/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlKamServer).Login(ctx, req.(*UserCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControlKam_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ctrlkm.ControlKam",
	HandlerType: (*ControlKamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _ControlKam_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ctrlkm.proto",
}
