
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: ekskam-system

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: ekskam-system
rules:
  - apiGroups:
      - "batch"
      - "extensions"
      - "apps"
    resources:
      - pods/portforward
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: ekskam-system
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: ekskam-system
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
