
apiVersion: v1
clusters:
  - cluster:
      server: https://6522E5FF071010AB2623C6131659C92C.sk1.us-east-1.eks.amazonaws.com
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNE1URXlPREl6TlRnME9Gb1hEVEk0TVRFeU5USXpOVGcwT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTC9XCjBDUVZBUDVFZzZDRkE5dmlLYndJd0xuZTV0OVZqWHpLZENpMlVqNmtCVEx6dUN6V25sU1BuSjdERFppeUw4NksKbVNWelc5TGJ0Z0c0eE52dE5FTk9YQlVXbUZhbEFhTENlbzFGN0NQTVhUQldBOVJ2NWJRSC92SklteldjT3RqbQpWNm1HaWV5N0FJSEhLTnNnUDlONktZejlEdGRyVENlc0JNblhqSG4wTlZKMHNEMkw1R2JjMFdTdW9yWHV1cDhoCnpzTjFLRTNjcGlrNzlzcjR3MC9jNzZLNVU4NUJJSkdVdHJRRExiemRIVFdranorazZyVFYvNUdmS3UxVHVwd28KdjA0c3dmWFlnWXJIb2pvM3NMWUw1dUhSaHc2VFN5dXova0ZzUEpCbXM2Z3V2bmFiT2lyc0cxMW4rOFp2aXhreAp6cDQxS0RzSEJFM1BQNWMvR0hNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDdCt1L3k0aER3THZVNlVmUXV6Vzltbk9NWUMKOFVIRE01TG5PbzhleUtGYkhNOFVJVEI2Z2VjdGFjaC9Ub2x6Z256RWJKOTJ5THU3SWhIR01TU0pES25XYWZVQwpVRThXeE5lcko0WHYvSCtZZlplTWpNcXg5cWM0cjViZ2MwVnpyY1lxV2YxdHBxRW5LYk5SaDY3aEExVE41eU1aCkZZYWRveHRCU24rUDZEcjAvWldlNmtjTGlEbXpyYzBYU1YzbjNUUEdxTjZ6Zlk2ZTRkK0J1NFBuQWdYR3NsUUgKVnF4VFhXU1hDdi90cTNSbjlidjIvd3lMRHhNbXJRMG50ZHZHZW12Z3Z2MXlWM3dnbG10WnJzN01ueWlUaW5NOApveUdCaVpJZjFFWDJUZkIyNHUxTmw5NlA5ei9kVzBHZDUrVmlmV2QvYmd5MGJ5eG40cE5pTC9kZFdvST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: aws
    name: aws
current-context: aws
kind: Config
preferences: {}
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: aws-iam-authenticator
        args:
          - "token"
          - "-i"
          - "ekskam-cluster"
